#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE="cats"

KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
HELM="$SNAP_DATA/bin/helm3 --kubeconfig=$SNAP_DATA/credentials/client.config"
KUBECTL_DELETE_ARGS="--wait=true --timeout=180s --ignore-not-found=true"

echo "Disabling cat-cozy"

$HELM delete cat-cozy -n $NAMESPACE_STARBOARD

$KUBECTL delete $KUBECTL_DELETE_ARGS namespace "$NAMESPACE" > /dev/null 2>&1 || true

echo "cat-cozy disabled"